name: flutter_weather_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter      
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  get_it: ^7.2.0
  equatable: ^2.0.3
  flutter_bloc: ^7.1.0
  json_annotation: ^4.0.1
  shared_preferences: ^2.0.6
  intl: ^0.17.0
  geolocator: ^7.4.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.4
  lints: ^1.0.1
  mockito: ^5.0.14

flutter:
  uses-material-design: true